### ISSUE TITLE
JAVA_TOOL_OPTIONS ant WebStorm launch for 2020.2 version

### ISSUE THREAD

**Issue by morissonmaciel** [flathub/com.jetbrains.WebStorm#23]
WebStorm 2020.2 give a warning when startup:

```The use of Java options environment variables detected. Such variables override IDE configuration files (*.vmoptions) and may cause performance and stability issues. Please consider deleting these variables: JAVA_TOOL_OPTIONS.```

Does JAVA_TOOL_OPTIONS is still necessary?

The DataGrip and IntelliJ flatpacks have already removed these options from `entrypoint.sh`

**Comment by FakeShemp** [comment]
Closed with #26
