### ISSUE TITLE
Can't find Node.js in WebStorm

### ISSUE THREAD

**Issue by liferooter** [flathub/com.jetbrains.WebStorm#28]
# Details
**OS:** Fedora Workstation 33
**Flatpak:** Flatpak 1.8.3
**App version:** Jetbrains WebStorm 2020.2.4
**Node version:** v14.14.0
**NPM vesion:** 6.14.8

# Steps to reproduce
1. Add Flathub repo to your Flatpak
2. Install com.jetbrains.WebStorm
3. Enable `host-os`, `host-etc` and `host` filesystem permissions for WebStorm
4. Run WebStorm
5. Open any Node.js project
6. Add build configuration
7. Try to build it

# Expected behavior
Project builds

# Real behavior
WebStorm indicates that you have no `node` and `npm` installed, but really I have. I can open GNOME Terminal and run `node` and `npm`. `which node` output is `/usr/bin/node`. But in WebStorm there is no `node` and `npm` installed although I've enabled host-os filesystem permission. In WebStorm terminal I've tested `node` presence and found out that there is no `node` binary in whole WebStorm app.

That's my`flatpak info --show-permissions com.jetbrains.WebStorm` output:
```
[Context]
shared=network;ipc;
sockets=x11;wayland;
devices=dri;
features=devel;
filesystems=host-os;host;

[Session Bus Policy]
org.freedesktop.Flatpak=talk
org.freedesktop.Notifications=talk
org.freedesktop.secrets=talk

[Environment]
WEBSTORM_JDK=/app/extra/webstorm/jre64
```

Thanks for your support and fixes.

**Comment by FakeShemp** [comment]
It's at `/var/run/host/usr/bin/node`

**Comment by liferooter** [comment]
I find out how to use runtime SDK extensions. I should install Flatpak SDK Node.js.
