### ISSUE TITLE
Failed to Install

### ISSUE THREAD

**Issue by bashoholic** [flathub/com.jetbrains.WebStorm#5]
Receiving the following error(s) when installing WebStorm via terminal or Gnome Software:

`Error: Wrong size for extra data https://download.jetbrains.com/webstorm/WebStorm-2019.1.3.tar.gz`

`error: Failed to install com.jetbrains.WebStorm: Wrong size for extra data https://download.jetbrains.com/webstorm/WebStorm-2019.1.3.tar.gz
`

**Comment by x80486** [comment]
Looks like I forgot to update the `size` in the manifest for version `2019.1.3`...let me push that really quick 😎
