### ISSUE TITLE
Some bugs noticed after upgrading to the latest version via toolbox

### ISSUE THREAD

**Issue by relaxdd** [flathub/com.jetbrains.WebStorm#76]
- When restarting the IDE, the settings in 'codestyle' fly off (turning off 'EditorConfig' did not help)
- Insertion into the editor (ctrl+v) stops working from time to time, it just doesn't do anything
- Sometimes in general, when inserting, spoiling html markup (which, for example, I copy from the browser or from somewhere else) turns out to be some kind of dirt

**Comment by FakeShemp** [comment]
What is the "toolbox"?

**Comment by relaxdd** [comment]
> What is the "toolbox"?

Jetbrains Toolbox

**Comment by x80486** [comment]
If you are referring to the `JetBrains Toolbox App`, the same is unable to install/update anything-Flatpak.

**Comment by relaxdd** [comment]
> If you are referring to the `JetBrains Toolbox App`, the same is unable to install/update anything-Flatpak.

what is 'Flatpak'? apparently I created the issue is not there where i need, I need the official jetbrains webstorm community
